title: Abandoned Plugins 
description: Supporting the WordPress community by maintaining useful plugins abandoned by other developers.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
